apiVersion: apps/v1
kind: Deployment
metadata:
  name: best-model-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: best-model-api
  template:
    metadata:
      labels:
        app: best-model-api
    spec:
      containers:
      - name: best-model-api
        image: best-model-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: best-model-api-service
spec:
  selector:
    app: best-model-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
  type: NodePort
