apiVersion: batch/v1
kind: Job
metadata:
  name: optuna-tuning-job
spec:
  parallelism: 4
  completions: 4
  template:
    spec:
      containers:
      - name: tuner
        image: hyperparameter-tuning:latest
        imagePullPolicy: Never
        env:
        - name: DB_URL
          value: "postgresql://user:password@postgres/optuna"
        volumeMounts:
        - name: result-volume
          mountPath: /app/results
      restartPolicy: Never
      volumes:
      - name: result-volume
        hostPath:
          path: /mnt/data/results
