name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.train
        pip install -r requirements.deploy

    - name: Run tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t best-model-api:latest -f Dockerfile.deploy .

    - name: Lowercase repository name and username
      id: vars
      run: |
        echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "USERNAME=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Push Docker image to GitHub Packages
      env:
        GHCR_PAT: ${{ secrets.GHCR_PAT }}
      run: |
        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ env.USERNAME }} --password-stdin
        docker tag best-model-api:latest ghcr.io/${{ env.USERNAME }}/${{ env.REPO_NAME }}/best-model-api:latest
        docker push ghcr.io/${{ env.USERNAME }}/${{ env.REPO_NAME }}/best-model-api:latest
